name: tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python3 -m pytest --md-report --md-report-flavor gfm --md-report-output md_report.md
      env:
        PYTHONPATH: ${{ github.workspace }}/src

    - name: Update summary
      if: always()
      run: |
        cat md_report.md >> $GITHUB_STEP_SUMMARY
